<?php
/**
 * CustomFieldsUpdateStrategy
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Aurigma\AssetStorage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AssetStorage API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Aurigma\AssetStorage\Model;
use \Aurigma\AssetStorage\ObjectSerializer;

/**
 * CustomFieldsUpdateStrategy Class Doc Comment
 *
 * @category Class
 * @description Custom fields update strategy.
 * @package  Aurigma\AssetStorage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CustomFieldsUpdateStrategy
{
    /**
     * Possible values of this enum
     */
    const MERGE = 'Merge';
    const REPLACE = 'Replace';
    const ADD = 'Add';
    const REMOVE = 'Remove';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::MERGE,
            self::REPLACE,
            self::ADD,
            self::REMOVE,
        ];
    }
}


