<?php
/**
 * DesignMetadata
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\AssetStorage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AssetStorage API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Aurigma\AssetStorage\Model;

use \ArrayAccess;
use \Aurigma\AssetStorage\ObjectSerializer;

/**
 * DesignMetadata Class Doc Comment
 *
 * @category Class
 * @description Design metadata.
 * @package  Aurigma\AssetStorage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class DesignMetadata implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'DesignMetadata';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'fonts' => '\Aurigma\AssetStorage\Model\DesignFontMetadata[]',
        'surfaces' => '\Aurigma\AssetStorage\Model\DesignSurfaceMetadata[]',
        'print_areas' => '\Aurigma\AssetStorage\Model\DesignPrintAreaMetadata[]',
        'has_data_schema' => 'bool',
        'data_schema_id' => 'string',
        'data_schema_name' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'fonts' => null,
        'surfaces' => null,
        'print_areas' => null,
        'has_data_schema' => null,
        'data_schema_id' => null,
        'data_schema_name' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'fonts' => true,
        'surfaces' => true,
        'print_areas' => true,
        'has_data_schema' => true,
        'data_schema_id' => true,
        'data_schema_name' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'fonts' => 'fonts',
        'surfaces' => 'surfaces',
        'print_areas' => 'printAreas',
        'has_data_schema' => 'hasDataSchema',
        'data_schema_id' => 'dataSchemaId',
        'data_schema_name' => 'dataSchemaName'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'fonts' => 'setFonts',
        'surfaces' => 'setSurfaces',
        'print_areas' => 'setPrintAreas',
        'has_data_schema' => 'setHasDataSchema',
        'data_schema_id' => 'setDataSchemaId',
        'data_schema_name' => 'setDataSchemaName'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'fonts' => 'getFonts',
        'surfaces' => 'getSurfaces',
        'print_areas' => 'getPrintAreas',
        'has_data_schema' => 'getHasDataSchema',
        'data_schema_id' => 'getDataSchemaId',
        'data_schema_name' => 'getDataSchemaName'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('fonts', $data ?? [], null);
        $this->setIfExists('surfaces', $data ?? [], null);
        $this->setIfExists('print_areas', $data ?? [], null);
        $this->setIfExists('has_data_schema', $data ?? [], null);
        $this->setIfExists('data_schema_id', $data ?? [], null);
        $this->setIfExists('data_schema_name', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets fonts
     *
     * @return \Aurigma\AssetStorage\Model\DesignFontMetadata[]|null
     */
    public function getFonts()
    {
        return $this->container['fonts'];
    }

    /**
     * Sets fonts
     *
     * @param \Aurigma\AssetStorage\Model\DesignFontMetadata[]|null $fonts Design font metadata list.
     *
     * @return self
     */
    public function setFonts($fonts)
    {
        if (is_null($fonts)) {
            array_push($this->openAPINullablesSetToNull, 'fonts');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('fonts', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['fonts'] = $fonts;

        return $this;
    }

    /**
     * Gets surfaces
     *
     * @return \Aurigma\AssetStorage\Model\DesignSurfaceMetadata[]|null
     */
    public function getSurfaces()
    {
        return $this->container['surfaces'];
    }

    /**
     * Sets surfaces
     *
     * @param \Aurigma\AssetStorage\Model\DesignSurfaceMetadata[]|null $surfaces Design surface metadata list.
     *
     * @return self
     */
    public function setSurfaces($surfaces)
    {
        if (is_null($surfaces)) {
            array_push($this->openAPINullablesSetToNull, 'surfaces');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('surfaces', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['surfaces'] = $surfaces;

        return $this;
    }

    /**
     * Gets print_areas
     *
     * @return \Aurigma\AssetStorage\Model\DesignPrintAreaMetadata[]|null
     */
    public function getPrintAreas()
    {
        return $this->container['print_areas'];
    }

    /**
     * Sets print_areas
     *
     * @param \Aurigma\AssetStorage\Model\DesignPrintAreaMetadata[]|null $print_areas Design print area metadata list.
     *
     * @return self
     */
    public function setPrintAreas($print_areas)
    {
        if (is_null($print_areas)) {
            array_push($this->openAPINullablesSetToNull, 'print_areas');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('print_areas', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['print_areas'] = $print_areas;

        return $this;
    }

    /**
     * Gets has_data_schema
     *
     * @return bool|null
     */
    public function getHasDataSchema()
    {
        return $this->container['has_data_schema'];
    }

    /**
     * Sets has_data_schema
     *
     * @param bool|null $has_data_schema Indicates whether design has data schema.
     *
     * @return self
     */
    public function setHasDataSchema($has_data_schema)
    {
        if (is_null($has_data_schema)) {
            array_push($this->openAPINullablesSetToNull, 'has_data_schema');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('has_data_schema', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['has_data_schema'] = $has_data_schema;

        return $this;
    }

    /**
     * Gets data_schema_id
     *
     * @return string|null
     */
    public function getDataSchemaId()
    {
        return $this->container['data_schema_id'];
    }

    /**
     * Sets data_schema_id
     *
     * @param string|null $data_schema_id Design data schema identifier. Empty string for embedded schema.
     *
     * @return self
     */
    public function setDataSchemaId($data_schema_id)
    {
        if (is_null($data_schema_id)) {
            array_push($this->openAPINullablesSetToNull, 'data_schema_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('data_schema_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['data_schema_id'] = $data_schema_id;

        return $this;
    }

    /**
     * Gets data_schema_name
     *
     * @return string|null
     */
    public function getDataSchemaName()
    {
        return $this->container['data_schema_name'];
    }

    /**
     * Sets data_schema_name
     *
     * @param string|null $data_schema_name Design data schema name.
     *
     * @return self
     */
    public function setDataSchemaName($data_schema_name)
    {
        if (is_null($data_schema_name)) {
            array_push($this->openAPINullablesSetToNull, 'data_schema_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('data_schema_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['data_schema_name'] = $data_schema_name;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


