<?php
/**
 * MockupType
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Aurigma\AssetStorage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AssetStorage API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Aurigma\AssetStorage\Model;
use \Aurigma\AssetStorage\ObjectSerializer;

/**
 * MockupType Class Doc Comment
 *
 * @category Class
 * @description Mockup type.
 * @package  Aurigma\AssetStorage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MockupType
{
    /**
     * Possible values of this enum
     */
    const MOCKUP2_D = 'Mockup2D';
    const MOCKUP3_D = 'Mockup3D';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::MOCKUP2_D,
            self::MOCKUP3_D,
        ];
    }
}


