<?php
/**
 * MockupType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\AssetStorage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Asset Storage API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Aurigma\AssetStorage\Model;
use \Aurigma\AssetStorage\ObjectSerializer;

/**
 * MockupType Class Doc Comment
 *
 * @category Class
 * @package  Aurigma\AssetStorage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MockupType
{
    /**
     * Possible values of this enum
     */
    public const MOCKUP2_D = 'Mockup2D';

    public const MOCKUP3_D = 'Mockup3D';

    public const MOCKUP_LINK = 'MockupLink';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::MOCKUP2_D,
            self::MOCKUP3_D,
            self::MOCKUP_LINK
        ];
    }
}


