<?php
/**
 * BatchUpdateParentFolderInputTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\AssetStorage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Asset Storage API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Aurigma\AssetStorage\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * BatchUpdateParentFolderInputTest Class Doc Comment
 *
 * @category    Class
 * @description DTO, containing parameters for batch update parent folder operation.
 * @package     Aurigma\AssetStorage
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class BatchUpdateParentFolderInputTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "BatchUpdateParentFolderInput"
     */
    public function testBatchUpdateParentFolderInput()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "entity_ids"
     */
    public function testPropertyEntityIds()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "folder_ids"
     */
    public function testPropertyFolderIds()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "path"
     */
    public function testPropertyPath()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "conflict_strategy"
     */
    public function testPropertyConflictStrategy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
