<?php
/**
 * ColorSpaceTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Aurigma\AssetStorage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AssetStorage API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Aurigma\AssetStorage\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ColorSpaceTest Class Doc Comment
 *
 * @category    Class
 * @description Color space
 * @package     Aurigma\AssetStorage
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ColorSpaceTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ColorSpace"
     */
    public function testColorSpace()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
