<?php
/**
 * ColorProfilesApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\AssetStorage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Asset Storage API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Aurigma\AssetStorage\Test\Api;

use \Aurigma\AssetStorage\Configuration;
use \Aurigma\AssetStorage\ApiException;
use \Aurigma\AssetStorage\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ColorProfilesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Aurigma\AssetStorage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ColorProfilesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for colorProfilesBatchCopy
     *
     * Copies the specified entities and folders to another folder..
     *
     */
    public function testColorProfilesBatchCopy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for colorProfilesBatchDelete
     *
     * Deletes the specified entities and folders..
     *
     */
    public function testColorProfilesBatchDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for colorProfilesBatchUpdateCustomFields
     *
     * Updates custom fields values for the specified entities..
     *
     */
    public function testColorProfilesBatchUpdateCustomFields()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for colorProfilesBatchUpdateParentFolder
     *
     * Updates parent folder for the specified entities and folders..
     *
     */
    public function testColorProfilesBatchUpdateParentFolder()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for colorProfilesCopy
     *
     * Copies the specified entity..
     *
     */
    public function testColorProfilesCopy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for colorProfilesCreate
     *
     * Creates a new entity..
     *
     */
    public function testColorProfilesCreate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for colorProfilesCreateFolder
     *
     * Creates a new folder..
     *
     */
    public function testColorProfilesCreateFolder()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for colorProfilesDelete
     *
     * Deletes the specified entity..
     *
     */
    public function testColorProfilesDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for colorProfilesDeleteFolder
     *
     * Deletes the specified folder and its content by folder path..
     *
     */
    public function testColorProfilesDeleteFolder()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for colorProfilesDeleteFolderById
     *
     * Deletes the specified folder and its content by folder identifier..
     *
     */
    public function testColorProfilesDeleteFolderById()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for colorProfilesGet
     *
     * Returns an entity by ID..
     *
     */
    public function testColorProfilesGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for colorProfilesGetAll
     *
     * Returns all entities relevant to specified query parameters..
     *
     */
    public function testColorProfilesGetAll()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for colorProfilesGetAllFolders
     *
     * Returns all folders..
     *
     */
    public function testColorProfilesGetAllFolders()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for colorProfilesGetFile
     *
     * Returns an entity file from file storage..
     *
     */
    public function testColorProfilesGetFile()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for colorProfilesGetFileStorageInfo
     *
     * Returns information about the use of file storage..
     *
     */
    public function testColorProfilesGetFileStorageInfo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for colorProfilesGetFolderContent
     *
     * Returns a folder and its content by folder path..
     *
     */
    public function testColorProfilesGetFolderContent()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for colorProfilesGetFolderContentById
     *
     * Returns a folder and its content by folder ID..
     *
     */
    public function testColorProfilesGetFolderContentById()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for colorProfilesGetFolderInfo
     *
     * Returns a folder by ID..
     *
     */
    public function testColorProfilesGetFolderInfo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for colorProfilesUpdate
     *
     * Updates the specified entity..
     *
     */
    public function testColorProfilesUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for colorProfilesUpdateFolder
     *
     * Updates the specified folder..
     *
     */
    public function testColorProfilesUpdateFolder()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
