<?php
/**
 * ColorProfilesApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  Aurigma\AssetStorage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AssetStorage API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Aurigma\AssetStorage\Test\Api;

use \Aurigma\AssetStorage\Configuration;
use \Aurigma\AssetStorage\ApiException;
use \Aurigma\AssetStorage\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ColorProfilesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Aurigma\AssetStorage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ColorProfilesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for colorProfilesBatchCopy
     *
     * Copies selected entities and folders to another folder specified by path.
     *
     */
    public function testColorProfilesBatchCopy()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for colorProfilesBatchDelete
     *
     * Deletes selected entities and folders.
     *
     */
    public function testColorProfilesBatchDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for colorProfilesBatchUpdateParentFolder
     *
     * Updates parent folder for selected entities and folders.
     *
     */
    public function testColorProfilesBatchUpdateParentFolder()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for colorProfilesCopy
     *
     * Copies specified entity.
     *
     */
    public function testColorProfilesCopy()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for colorProfilesCreate
     *
     * Creates new entity.
     *
     */
    public function testColorProfilesCreate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for colorProfilesCreateCollection
     *
     * Creates new collection.
     *
     */
    public function testColorProfilesCreateCollection()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for colorProfilesCreateFolder
     *
     * Creates new folder.
     *
     */
    public function testColorProfilesCreateFolder()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for colorProfilesDelete
     *
     * Deletes specified entity.
     *
     */
    public function testColorProfilesDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for colorProfilesDeleteCollection
     *
     * Deletes specified collection.
     *
     */
    public function testColorProfilesDeleteCollection()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for colorProfilesDeleteFolder
     *
     * Deletes specified folder.
     *
     */
    public function testColorProfilesDeleteFolder()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for colorProfilesGet
     *
     * Gets entity by id.
     *
     */
    public function testColorProfilesGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for colorProfilesGetAll
     *
     * Gets all entities relevant to specified query parameters.
     *
     */
    public function testColorProfilesGetAll()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for colorProfilesGetAllCollections
     *
     * Gets all collections.
     *
     */
    public function testColorProfilesGetAllCollections()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for colorProfilesGetAllFolders
     *
     * Gets all folders.
     *
     */
    public function testColorProfilesGetAllFolders()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for colorProfilesGetCollection
     *
     * Gets collection content by collection id.
     *
     */
    public function testColorProfilesGetCollection()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for colorProfilesGetFile
     *
     * Gets entity file from file storage.
     *
     */
    public function testColorProfilesGetFile()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for colorProfilesGetFolder
     *
     * Gets folder content by folder path.
     *
     */
    public function testColorProfilesGetFolder()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for colorProfilesGetFolderInfo
     *
     * Gets folder by id.
     *
     */
    public function testColorProfilesGetFolderInfo()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for colorProfilesUpdate
     *
     * Updates specified entity.
     *
     */
    public function testColorProfilesUpdate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for colorProfilesUpdateCollection
     *
     * Updates specified collection.
     *
     */
    public function testColorProfilesUpdateCollection()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for colorProfilesUpdateFolder
     *
     * Updates specified folder.
     *
     */
    public function testColorProfilesUpdateFolder()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
