<?php
/**
 * DataSetsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\AssetStorage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Asset Storage API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Aurigma\AssetStorage\Test\Api;

use \Aurigma\AssetStorage\Configuration;
use \Aurigma\AssetStorage\ApiException;
use \Aurigma\AssetStorage\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DataSetsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Aurigma\AssetStorage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DataSetsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for dataSetsBatchCopy
     *
     * Copies the specified entities and folders to another folder..
     *
     */
    public function testDataSetsBatchCopy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSetsBatchDelete
     *
     * Deletes the specified entities and folders..
     *
     */
    public function testDataSetsBatchDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSetsBatchUpdateCustomFields
     *
     * Updates custom fields values for the specified entities..
     *
     */
    public function testDataSetsBatchUpdateCustomFields()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSetsBatchUpdateParentFolder
     *
     * Updates parent folder for the specified entities and folders..
     *
     */
    public function testDataSetsBatchUpdateParentFolder()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSetsCopy
     *
     * Copies the specified entity..
     *
     */
    public function testDataSetsCopy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSetsCreate
     *
     * Creates a new entity..
     *
     */
    public function testDataSetsCreate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSetsCreateFolder
     *
     * Creates a new folder..
     *
     */
    public function testDataSetsCreateFolder()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSetsDelete
     *
     * Deletes the specified entity..
     *
     */
    public function testDataSetsDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSetsDeleteFolder
     *
     * Deletes the specified folder and its content by folder path..
     *
     */
    public function testDataSetsDeleteFolder()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSetsDeleteFolderById
     *
     * Deletes the specified folder and its content by folder identifier..
     *
     */
    public function testDataSetsDeleteFolderById()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSetsGet
     *
     * Returns an entity by ID..
     *
     */
    public function testDataSetsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSetsGetAll
     *
     * Returns all entities relevant to specified query parameters..
     *
     */
    public function testDataSetsGetAll()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSetsGetAllFolders
     *
     * Returns all folders..
     *
     */
    public function testDataSetsGetAllFolders()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSetsGetFile
     *
     * Returns an entity file from file storage..
     *
     */
    public function testDataSetsGetFile()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSetsGetFileStorageInfo
     *
     * Returns information about the use of file storage..
     *
     */
    public function testDataSetsGetFileStorageInfo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSetsGetFolderContent
     *
     * Returns a folder and its content by folder path..
     *
     */
    public function testDataSetsGetFolderContent()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSetsGetFolderContentById
     *
     * Returns a folder and its content by folder ID..
     *
     */
    public function testDataSetsGetFolderContentById()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSetsGetFolderInfo
     *
     * Returns a folder by ID..
     *
     */
    public function testDataSetsGetFolderInfo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSetsUpdate
     *
     * Updates the specified entity..
     *
     */
    public function testDataSetsUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSetsUpdateFolder
     *
     * Updates the specified folder..
     *
     */
    public function testDataSetsUpdateFolder()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
