<?php
/**
 * DataSchemasApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  Aurigma\AssetStorage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AssetStorage API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Aurigma\AssetStorage\Test\Api;

use \Aurigma\AssetStorage\Configuration;
use \Aurigma\AssetStorage\ApiException;
use \Aurigma\AssetStorage\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DataSchemasApiTest Class Doc Comment
 *
 * @category Class
 * @package  Aurigma\AssetStorage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DataSchemasApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for dataSchemasBatchCopy
     *
     * Copies selected entities and folders to another folder specified by path.
     *
     */
    public function testDataSchemasBatchCopy()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSchemasBatchDelete
     *
     * Deletes selected entities and folders.
     *
     */
    public function testDataSchemasBatchDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSchemasBatchUpdateParentFolder
     *
     * Updates parent folder for selected entities and folders.
     *
     */
    public function testDataSchemasBatchUpdateParentFolder()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSchemasCopy
     *
     * Copies specified entity.
     *
     */
    public function testDataSchemasCopy()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSchemasCreate
     *
     * Creates new entity.
     *
     */
    public function testDataSchemasCreate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSchemasCreateCollection
     *
     * Creates new collection.
     *
     */
    public function testDataSchemasCreateCollection()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSchemasCreateFolder
     *
     * Creates new folder.
     *
     */
    public function testDataSchemasCreateFolder()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSchemasDelete
     *
     * Deletes specified entity.
     *
     */
    public function testDataSchemasDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSchemasDeleteCollection
     *
     * Deletes specified collection.
     *
     */
    public function testDataSchemasDeleteCollection()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSchemasDeleteFolder
     *
     * Deletes specified folder.
     *
     */
    public function testDataSchemasDeleteFolder()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSchemasGet
     *
     * Gets entity by id.
     *
     */
    public function testDataSchemasGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSchemasGetAll
     *
     * Gets all entities relevant to specified query parameters.
     *
     */
    public function testDataSchemasGetAll()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSchemasGetAllCollections
     *
     * Gets all collections.
     *
     */
    public function testDataSchemasGetAllCollections()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSchemasGetAllFolders
     *
     * Gets all folders.
     *
     */
    public function testDataSchemasGetAllFolders()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSchemasGetCollection
     *
     * Gets collection content by collection id.
     *
     */
    public function testDataSchemasGetCollection()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSchemasGetFile
     *
     * Gets entity file from file storage.
     *
     */
    public function testDataSchemasGetFile()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSchemasGetFolder
     *
     * Gets folder content by folder path.
     *
     */
    public function testDataSchemasGetFolder()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSchemasGetFolderInfo
     *
     * Gets folder by id.
     *
     */
    public function testDataSchemasGetFolderInfo()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSchemasUpdate
     *
     * Updates specified entity.
     *
     */
    public function testDataSchemasUpdate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSchemasUpdateCollection
     *
     * Updates specified collection.
     *
     */
    public function testDataSchemasUpdateCollection()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSchemasUpdateFolder
     *
     * Updates specified folder.
     *
     */
    public function testDataSchemasUpdateFolder()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
