<?php
/**
 * DataSchemasApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\AssetStorage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Asset Storage API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Aurigma\AssetStorage\Test\Api;

use \Aurigma\AssetStorage\Configuration;
use \Aurigma\AssetStorage\ApiException;
use \Aurigma\AssetStorage\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DataSchemasApiTest Class Doc Comment
 *
 * @category Class
 * @package  Aurigma\AssetStorage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DataSchemasApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for dataSchemasBatchCopy
     *
     * Copies the specified entities and folders to another folder..
     *
     */
    public function testDataSchemasBatchCopy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSchemasBatchDelete
     *
     * Deletes the specified entities and folders..
     *
     */
    public function testDataSchemasBatchDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSchemasBatchUpdateCustomFields
     *
     * Updates custom fields values for the specified entities..
     *
     */
    public function testDataSchemasBatchUpdateCustomFields()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSchemasBatchUpdateParentFolder
     *
     * Updates parent folder for the specified entities and folders..
     *
     */
    public function testDataSchemasBatchUpdateParentFolder()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSchemasCopy
     *
     * Copies the specified entity..
     *
     */
    public function testDataSchemasCopy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSchemasCreate
     *
     * Creates a new entity..
     *
     */
    public function testDataSchemasCreate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSchemasCreateFolder
     *
     * Creates a new folder..
     *
     */
    public function testDataSchemasCreateFolder()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSchemasDelete
     *
     * Deletes the specified entity..
     *
     */
    public function testDataSchemasDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSchemasDeleteFolder
     *
     * Deletes the specified folder and its content by folder path..
     *
     */
    public function testDataSchemasDeleteFolder()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSchemasDeleteFolderById
     *
     * Deletes the specified folder and its content by folder identifier..
     *
     */
    public function testDataSchemasDeleteFolderById()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSchemasGet
     *
     * Returns an entity by ID..
     *
     */
    public function testDataSchemasGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSchemasGetAll
     *
     * Returns all entities relevant to specified query parameters..
     *
     */
    public function testDataSchemasGetAll()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSchemasGetAllFolders
     *
     * Returns all folders..
     *
     */
    public function testDataSchemasGetAllFolders()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSchemasGetFile
     *
     * Returns an entity file from file storage..
     *
     */
    public function testDataSchemasGetFile()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSchemasGetFileStorageInfo
     *
     * Returns information about the use of file storage..
     *
     */
    public function testDataSchemasGetFileStorageInfo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSchemasGetFolder
     *
     * Returns a folder and its content by folder path..
     *
     */
    public function testDataSchemasGetFolder()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSchemasGetFolderInfo
     *
     * Returns a folder by ID..
     *
     */
    public function testDataSchemasGetFolderInfo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSchemasUpdate
     *
     * Updates the specified entity..
     *
     */
    public function testDataSchemasUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dataSchemasUpdateFolder
     *
     * Updates the specified folder..
     *
     */
    public function testDataSchemasUpdateFolder()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
