<?php
/**
 * DocumentsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\AssetStorage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Asset Storage API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Aurigma\AssetStorage\Test\Api;

use \Aurigma\AssetStorage\Configuration;
use \Aurigma\AssetStorage\ApiException;
use \Aurigma\AssetStorage\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DocumentsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Aurigma\AssetStorage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DocumentsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for documentsBatchCopy
     *
     * Copies the specified entities and folders to another folder..
     *
     */
    public function testDocumentsBatchCopy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for documentsBatchDelete
     *
     * Deletes the specified entities and folders..
     *
     */
    public function testDocumentsBatchDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for documentsBatchUpdateCustomFields
     *
     * Updates custom fields values for the specified entities..
     *
     */
    public function testDocumentsBatchUpdateCustomFields()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for documentsBatchUpdateParentFolder
     *
     * Updates parent folder for the specified entities and folders..
     *
     */
    public function testDocumentsBatchUpdateParentFolder()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for documentsCopy
     *
     * Copies the specified entity..
     *
     */
    public function testDocumentsCopy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for documentsCreate
     *
     * Creates a new entity..
     *
     */
    public function testDocumentsCreate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for documentsCreateFolder
     *
     * Creates a new folder..
     *
     */
    public function testDocumentsCreateFolder()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for documentsDelete
     *
     * Deletes the specified entity..
     *
     */
    public function testDocumentsDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for documentsDeleteFolder
     *
     * Deletes the specified folder and its content by folder path..
     *
     */
    public function testDocumentsDeleteFolder()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for documentsDeleteFolderById
     *
     * Deletes the specified folder and its content by folder identifier..
     *
     */
    public function testDocumentsDeleteFolderById()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for documentsGet
     *
     * Returns an entity by ID..
     *
     */
    public function testDocumentsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for documentsGetAll
     *
     * Returns all entities relevant to specified query parameters..
     *
     */
    public function testDocumentsGetAll()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for documentsGetAllFolders
     *
     * Returns all folders..
     *
     */
    public function testDocumentsGetAllFolders()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for documentsGetFile
     *
     * Returns an entity file from file storage..
     *
     */
    public function testDocumentsGetFile()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for documentsGetFileStorageInfo
     *
     * Returns information about the use of file storage..
     *
     */
    public function testDocumentsGetFileStorageInfo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for documentsGetFolder
     *
     * Returns a folder and its content by folder path..
     *
     */
    public function testDocumentsGetFolder()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for documentsGetFolderInfo
     *
     * Returns a folder by ID..
     *
     */
    public function testDocumentsGetFolderInfo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for documentsUpdate
     *
     * Updates the specified entity..
     *
     */
    public function testDocumentsUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for documentsUpdateFolder
     *
     * Updates the specified folder..
     *
     */
    public function testDocumentsUpdateFolder()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
