<?php
/**
 * FontsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\AssetStorage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Asset Storage API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Aurigma\AssetStorage\Test\Api;

use \Aurigma\AssetStorage\Configuration;
use \Aurigma\AssetStorage\ApiException;
use \Aurigma\AssetStorage\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * FontsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Aurigma\AssetStorage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FontsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for fontsAddPreview
     *
     * Creates a preview entity for specified source entity..
     *
     */
    public function testFontsAddPreview()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for fontsBatchCopy
     *
     * Copies the specified entities and folders to another folder..
     *
     */
    public function testFontsBatchCopy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for fontsBatchDelete
     *
     * Deletes the specified entities and folders..
     *
     */
    public function testFontsBatchDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for fontsBatchUpdateCustomFields
     *
     * Updates custom fields values for the specified entities..
     *
     */
    public function testFontsBatchUpdateCustomFields()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for fontsBatchUpdateParentFolder
     *
     * Updates parent folder for the specified entities and folders..
     *
     */
    public function testFontsBatchUpdateParentFolder()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for fontsCopy
     *
     * Copies the specified entity..
     *
     */
    public function testFontsCopy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for fontsCreate
     *
     * Creates a new entity..
     *
     */
    public function testFontsCreate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for fontsCreateFolder
     *
     * Creates a new folder..
     *
     */
    public function testFontsCreateFolder()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for fontsDelete
     *
     * Deletes the specified entity..
     *
     */
    public function testFontsDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for fontsDeleteFolder
     *
     * Deletes the specified folder and its content by folder path..
     *
     */
    public function testFontsDeleteFolder()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for fontsDeleteFolderById
     *
     * Deletes the specified folder and its content by folder identifier..
     *
     */
    public function testFontsDeleteFolderById()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for fontsGet
     *
     * Returns an entity by ID..
     *
     */
    public function testFontsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for fontsGetAll
     *
     * Returns all entities relevant to specified query parameters..
     *
     */
    public function testFontsGetAll()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for fontsGetAllFolders
     *
     * Returns all folders..
     *
     */
    public function testFontsGetAllFolders()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for fontsGetFile
     *
     * Returns an entity file from file storage..
     *
     */
    public function testFontsGetFile()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for fontsGetFileStorageInfo
     *
     * Returns information about the use of file storage..
     *
     */
    public function testFontsGetFileStorageInfo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for fontsGetFolder
     *
     * Returns a folder and its content by folder path..
     *
     */
    public function testFontsGetFolder()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for fontsGetFolderInfo
     *
     * Returns a folder by ID..
     *
     */
    public function testFontsGetFolderInfo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for fontsUpdate
     *
     * Updates the specified entity..
     *
     */
    public function testFontsUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for fontsUpdateFolder
     *
     * Updates the specified folder..
     *
     */
    public function testFontsUpdateFolder()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
