<?php
/**
 * PalettesApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\AssetStorage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Asset Storage API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Aurigma\AssetStorage\Test\Api;

use \Aurigma\AssetStorage\Configuration;
use \Aurigma\AssetStorage\ApiException;
use \Aurigma\AssetStorage\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PalettesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Aurigma\AssetStorage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PalettesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for palettesAddPreview
     *
     * Creates a preview entity for specified source entity..
     *
     */
    public function testPalettesAddPreview()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for palettesBatchCopy
     *
     * Copies the specified entities and folders to another folder..
     *
     */
    public function testPalettesBatchCopy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for palettesBatchDelete
     *
     * Deletes the specified entities and folders..
     *
     */
    public function testPalettesBatchDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for palettesBatchUpdateCustomFields
     *
     * Updates custom fields values for the specified entities..
     *
     */
    public function testPalettesBatchUpdateCustomFields()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for palettesBatchUpdateParentFolder
     *
     * Updates parent folder for the specified entities and folders..
     *
     */
    public function testPalettesBatchUpdateParentFolder()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for palettesCopy
     *
     * Copies the specified entity..
     *
     */
    public function testPalettesCopy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for palettesCreate
     *
     * Creates a new entity..
     *
     */
    public function testPalettesCreate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for palettesCreateFolder
     *
     * Creates a new folder..
     *
     */
    public function testPalettesCreateFolder()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for palettesDelete
     *
     * Deletes the specified entity..
     *
     */
    public function testPalettesDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for palettesDeleteFolder
     *
     * Deletes the specified folder and its content by folder path..
     *
     */
    public function testPalettesDeleteFolder()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for palettesDeleteFolderById
     *
     * Deletes the specified folder and its content by folder identifier..
     *
     */
    public function testPalettesDeleteFolderById()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for palettesGet
     *
     * Returns an entity by ID..
     *
     */
    public function testPalettesGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for palettesGetAll
     *
     * Returns all entities relevant to specified query parameters..
     *
     */
    public function testPalettesGetAll()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for palettesGetAllFolders
     *
     * Returns all folders..
     *
     */
    public function testPalettesGetAllFolders()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for palettesGetFile
     *
     * Returns an entity file from file storage..
     *
     */
    public function testPalettesGetFile()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for palettesGetFileStorageInfo
     *
     * Returns information about the use of file storage..
     *
     */
    public function testPalettesGetFileStorageInfo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for palettesGetFolder
     *
     * Returns a folder and its content by folder path..
     *
     */
    public function testPalettesGetFolder()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for palettesGetFolderInfo
     *
     * Returns a folder by ID..
     *
     */
    public function testPalettesGetFolderInfo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for palettesUpdate
     *
     * Updates the specified entity..
     *
     */
    public function testPalettesUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for palettesUpdateFolder
     *
     * Updates the specified folder..
     *
     */
    public function testPalettesUpdateFolder()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
