<?php
/**
 * PrivateMockupsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\AssetStorage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Asset Storage API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Aurigma\AssetStorage\Test\Api;

use \Aurigma\AssetStorage\Configuration;
use \Aurigma\AssetStorage\ApiException;
use \Aurigma\AssetStorage\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PrivateMockupsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Aurigma\AssetStorage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PrivateMockupsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for privateMockupsAddPreview
     *
     * Creates a preview entity for specified source entity..
     *
     */
    public function testPrivateMockupsAddPreview()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for privateMockupsBatchCopy
     *
     * Copies the specified entities and folders to another folder..
     *
     */
    public function testPrivateMockupsBatchCopy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for privateMockupsBatchDelete
     *
     * Deletes the specified entities and folders..
     *
     */
    public function testPrivateMockupsBatchDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for privateMockupsBatchUpdateCustomFields
     *
     * Updates custom fields values for the specified entities..
     *
     */
    public function testPrivateMockupsBatchUpdateCustomFields()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for privateMockupsBatchUpdateOwner
     *
     * Updates owner for the specified entities and folders..
     *
     */
    public function testPrivateMockupsBatchUpdateOwner()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for privateMockupsBatchUpdateParentFolder
     *
     * Updates parent folder for the specified entities and folders..
     *
     */
    public function testPrivateMockupsBatchUpdateParentFolder()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for privateMockupsCopy
     *
     * Copies the specified entity..
     *
     */
    public function testPrivateMockupsCopy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for privateMockupsCreate
     *
     * Creates a new entity..
     *
     */
    public function testPrivateMockupsCreate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for privateMockupsCreateFolder
     *
     * Creates a new folder..
     *
     */
    public function testPrivateMockupsCreateFolder()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for privateMockupsDelete
     *
     * Deletes the specified entity..
     *
     */
    public function testPrivateMockupsDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for privateMockupsDeleteFolder
     *
     * Deletes the specified folder and its content by folder path..
     *
     */
    public function testPrivateMockupsDeleteFolder()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for privateMockupsDeleteFolderById
     *
     * Deletes the specified folder and its content by folder identifier..
     *
     */
    public function testPrivateMockupsDeleteFolderById()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for privateMockupsGet
     *
     * Returns an entity by ID..
     *
     */
    public function testPrivateMockupsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for privateMockupsGetAll
     *
     * Returns all entities relevant to specified query parameters..
     *
     */
    public function testPrivateMockupsGetAll()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for privateMockupsGetAllFolders
     *
     * Returns all folders..
     *
     */
    public function testPrivateMockupsGetAllFolders()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for privateMockupsGetFile
     *
     * Returns an entity file from file storage..
     *
     */
    public function testPrivateMockupsGetFile()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for privateMockupsGetFileStorageInfo
     *
     * Returns information about the use of file storage..
     *
     */
    public function testPrivateMockupsGetFileStorageInfo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for privateMockupsGetFolderContent
     *
     * Returns a folder and its content by folder path..
     *
     */
    public function testPrivateMockupsGetFolderContent()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for privateMockupsGetFolderContentById
     *
     * Returns a folder and its content by folder id..
     *
     */
    public function testPrivateMockupsGetFolderContentById()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for privateMockupsGetFolderInfo
     *
     * Returns a folder by ID..
     *
     */
    public function testPrivateMockupsGetFolderInfo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for privateMockupsGetRetentionPolicy
     *
     * Returns an entity retention policy by entity identifier..
     *
     */
    public function testPrivateMockupsGetRetentionPolicy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for privateMockupsSetRetentionPolicy
     *
     * Updates an entity retention policy by entity identifier..
     *
     */
    public function testPrivateMockupsSetRetentionPolicy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for privateMockupsUpdate
     *
     * Updates the specified entity..
     *
     */
    public function testPrivateMockupsUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for privateMockupsUpdateFolder
     *
     * Updates the specified folder..
     *
     */
    public function testPrivateMockupsUpdateFolder()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
