<?php
/**
 * PrivateResourcesApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\AssetStorage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Asset Storage API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Aurigma\AssetStorage\Test\Api;

use \Aurigma\AssetStorage\Configuration;
use \Aurigma\AssetStorage\ApiException;
use \Aurigma\AssetStorage\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PrivateResourcesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Aurigma\AssetStorage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PrivateResourcesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for privateResourcesBatchCopy
     *
     * Copies the specified entities..
     *
     */
    public function testPrivateResourcesBatchCopy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for privateResourcesBatchDelete
     *
     * Deletes the specified entities..
     *
     */
    public function testPrivateResourcesBatchDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for privateResourcesBatchUpdateCustomFields
     *
     * Updates custom fields values for the specified entities..
     *
     */
    public function testPrivateResourcesBatchUpdateCustomFields()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for privateResourcesBatchUpdateOwner
     *
     * Updates owner for the specified entities..
     *
     */
    public function testPrivateResourcesBatchUpdateOwner()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for privateResourcesCopy
     *
     * Copies the specified entity..
     *
     */
    public function testPrivateResourcesCopy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for privateResourcesCreate
     *
     * Creates a new entity..
     *
     */
    public function testPrivateResourcesCreate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for privateResourcesDelete
     *
     * Deletes the specified entity..
     *
     */
    public function testPrivateResourcesDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for privateResourcesDeleteByNamespace
     *
     * Deletes all resources that use a specified namespace..
     *
     */
    public function testPrivateResourcesDeleteByNamespace()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for privateResourcesGet
     *
     * Returns an entity by ID..
     *
     */
    public function testPrivateResourcesGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for privateResourcesGetAll
     *
     * Returns all entities relevant to specified query parameters..
     *
     */
    public function testPrivateResourcesGetAll()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for privateResourcesGetFile
     *
     * Returns an entity file from file storage..
     *
     */
    public function testPrivateResourcesGetFile()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for privateResourcesGetFileStorageInfo
     *
     * Returns information about storage usage by private resource files..
     *
     */
    public function testPrivateResourcesGetFileStorageInfo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for privateResourcesGetRetentionPolicy
     *
     * Returns an entity retention policy by entity identifier..
     *
     */
    public function testPrivateResourcesGetRetentionPolicy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for privateResourcesSetRetentionPolicy
     *
     * Updates an entity retention policy by entity identifier..
     *
     */
    public function testPrivateResourcesSetRetentionPolicy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for privateResourcesUpdate
     *
     * Updates the specified entity..
     *
     */
    public function testPrivateResourcesUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
