<?php
/**
 * ResourcesApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\AssetStorage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Asset Storage API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Aurigma\AssetStorage\Test\Api;

use \Aurigma\AssetStorage\Configuration;
use \Aurigma\AssetStorage\ApiException;
use \Aurigma\AssetStorage\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ResourcesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Aurigma\AssetStorage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ResourcesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for resourcesBatchCopy
     *
     * Copies the specified entities..
     *
     */
    public function testResourcesBatchCopy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for resourcesBatchDelete
     *
     * Deletes the specified entities..
     *
     */
    public function testResourcesBatchDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for resourcesBatchUpdateCustomFields
     *
     * Updates custom fields values for the specified entities..
     *
     */
    public function testResourcesBatchUpdateCustomFields()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for resourcesCopy
     *
     * Copies the specified entity..
     *
     */
    public function testResourcesCopy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for resourcesCreate
     *
     * Creates a new entity..
     *
     */
    public function testResourcesCreate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for resourcesDelete
     *
     * Deletes the specified entity..
     *
     */
    public function testResourcesDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for resourcesDeleteByNamespace
     *
     * Deletes all resources that use a specified namespace..
     *
     */
    public function testResourcesDeleteByNamespace()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for resourcesGet
     *
     * Returns an entity by ID..
     *
     */
    public function testResourcesGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for resourcesGetAll
     *
     * Returns all entities relevant to specified query parameters..
     *
     */
    public function testResourcesGetAll()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for resourcesGetFile
     *
     * Returns an entity file from file storage..
     *
     */
    public function testResourcesGetFile()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for resourcesGetFileStorageInfo
     *
     * Returns information about storage usage by resource files..
     *
     */
    public function testResourcesGetFileStorageInfo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for resourcesUpdate
     *
     * Updates the specified entity..
     *
     */
    public function testResourcesUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
